shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
